---
title: "使用图形工具创建 CSV 报告"
description: "使用图形工具 Postman 创建报告。"
products: 
    - "报告"
introduction: 
    title: "介绍"
    description: "使用图形工具 Postman 创建报告。"
    content: "# 简介\n\n本教程介绍如何使用图形工具 [Postman](https://www.getpostman.com/) 创建报告。Postman 的图形界面极大地降低了非技术用户与 Reports API 交互的复杂性。\n\n> 如果您还没有安装 Postman，请 [下载并安装](https://www.getpostman.com/downloads/)。\n"
tasks: 
    - "reports/create-report-postman"
    - "reports/check-report-status-postman"
    - "reports/download-report-postman"
    - "reports/reports-whats-next"
