title: Create Session
description: Use the Vonage Video Node.js SDK to learn how to create a session. Sessions allow participants to use audio, video, and messaging functionality in your application.
products:
  - video


introduction:
  title: Introduction
  description: In this tutorial, you will learn how to connect to a session from your web frontend.
  content: |
    # Introduction
    You can use the Vonage Video Node.js library to generate Vonage Video sessions. Each session has a unique session ID, which you can use in an OpenTok client library to connect to an Vonage Video session. (See ["Joining a Session"](/video/tutorials/joining-a-session)

    For general information regarding creating a session, see [Session Creation](/video/guides/create-session).

    Get started by fullfiling the [prerequisites](/video/tutorials/joining-a-session/prerequisites/node).

prerequisites:
  - video/general-prerequisites/video-api-account

tasks:
    - video/create-a-session/node/create-session-media-router
    - video/create-a-session/node/create-relayed-session
    - video/create-a-session/node/create-auto-archived
    - video/create-a-session/node/use-session-client-apps



conclusion:
  title: What's next?
  description: The next step is to integrate the server-side SDK to handle authentication
  content: |

    # What's next?
    You can learn more about the video platform concepts used in this tutorial from the [overview page](/video/overview).

    If you happen to have any ideas in mind please contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
