title: Debugging 
description: Learn how to use the debugging tools the video platform provides
products:
  - video

introduction:
  title: Introduction
  description: In this tutorial, you will learn how to debug your web frontend when working with the [Android Client SDK](/video/client-sdks/android/overview).
  content: |
    # Introduction
    In this tutorial, you will learn how to debug your web frontend when working with the [Android Client SDK](/video/client-sdks/android/overview).

tasks:
    - video/debugging/android/debugging



conclusion:
  title: What's next?
  description: Learn how to use the debugging tools the video platform provides.
  content: |

    # What's next?
    You can learn more about the video platform concepts used in this tutorial from the [overview page](/video/overview).

    If you happen to have any ideas in mind please contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
