---
title: "使用命令行创建 CSV 报告"
description: "使用命令行工具 Curl 创建 CSV 报告。"
products: 
    - "报告"
introduction: 
    title: "介绍"
    description: "指南 - 了解如何使用 Reports API"
    content: "# 简介\n\n本教程向您介绍如何使用 Reports API 的异步版本来创建和检索报告。\n\n要生成报告，请向 ASYNC 端点提交报告生成请求，然后等待其处理。\n\nReports API 检查请求的格式是否正确，然后将其放入处理队列中。它使用链接进行响应，点击该链接即可查看报告的当前状态。Reports API 还可以发送回调，以便在生成报告时通知您的应用程序。\n\n> **性能的说明**：即使 Reports API 运行速度快，可以处理大量数据，但在尝试下载用于实时分析的数据时，其运行速度可能会变慢。使用合理的过滤器可以大大加快处理速度。此外，若要频繁和定期检索小批量数据记录，请考虑使用 Reports API 的同步版本。\n"
tasks: 
    - "reports/create-report"
    - "reports/check-report-status"
    - "reports/download-report"
    - "reports/reports-whats-next"
