title: Subscribe to streams
description: Learn how to subscribe to a Vonage Video API stream in your iOS application. Once you have connected to a session, you can subscribe to a stream to view video, audio, and signalling data.
products:
  - video

introduction:
  title: Introduction
  description: In this tutorial, you will learn how to subscribe to a stream in an active sessions. 
  content: |
    # Introduction
    
    In In this tutorial, you will learn how to subscribe to a stream in an active sessions. Click **Next** to get started

tasks:
    - video/subscribe-streams/ios/2-detect-stream-created
    - video/subscribe-streams/ios/3-subscribe-to-stream
    - video/subscribe-streams/ios/4-auto-reconnect
    - video/subscribe-streams/ios/5-detect-stream-leaves-session
    - video/subscribe-streams/ios/6-get-stream-info
    - video/subscribe-streams/ios/7-set-frame-rate-resolution



conclusion:
  title: What's next?
  description: Learn how to use the subscribe-streams tools the video platform provides.
  content: |

    # What's next?
    You can learn more about the video platform concepts used in this tutorial from the [overview page](/video/overview).

    If you happen to have any ideas in mind please contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
