title: Generating session IDs and tokens on the server side
description: Generating session IDs and tokens on the server side.
products:
  - video

introduction:
  title: Introduction
  description: In this tutorial, you will learn how to integrate the video [SDK](/video/resources#client-sdks) on your frontend.
  content: |
    # Introduction

prerequisites:

tasks:


conclusion:
  title: What's next?
  description: The next step is to integrate the server-side SDK to handle authentication
  content: |

    # What's next?

    We want to hear what ideas you have in mind! Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
