title: Building a web-based video conferencing app
description: The video platform provides audio-video communication functionality for your web application.
products:
  - video

introduction:
  title: Introduction
  description: In this tutorial, you will learn how to integrate the video [SDK](/video/resources#client-sdks) on your frontend.
  content: |
    # Introduction
    In this tutorial, you will learn how to integrate the video [SDK](/video/resources#client-sdks) on your frontend.

    All applications that use the Vonage Video API are composed of two parts:

    - The client-side, which uses the [client SDKs](/video/resources#client-sdks) and runs in a user’s browser.
    - The server-side, which uses the [server SDKs](/video/resources#server-sdks) and runs on your server to pass authentication information to the client-side.
    
    The Client SDKs take care of the following:

    - Connecting to a session
    - Publishing streams to a session
    - Subscribing to streams in a session

    You can learn about the above concepts and SDKs on the [overview page](/video/overview).

    ### Completed project
    You will find the completed web client code in the **Basic Video Chat folder** of our [Web sample app GitHub repository](https://github.com/opentok/opentok-web-samples). The repo includes a README with documentation on how to run the code.

    *This tutorial uses [Opentok](https://www.npmjs.com/package/@opentok/client) version 2.0*.

prerequisites:
  - video/create-video-conferencing-app/prerequisites/javascript
  - video/video-api-account

tasks:
    - video/create-video-conferencing-app/javascript/folder-structure
    - video/create-video-conferencing-app/javascript/auth-setup

conclusion:
  title: What's next?
  description: The next step is to integrate the server-side SDK to handle authentication
  content: |

    # What's next?
    Once the frontend integration is complete, the next step is to [integrate the server-side SDK to handle authentication] (/video/tutorials/server-side-setup/introduction).

    You can also learn more about the video platform concepts via the [overview page](/video/overview).

    We want to hear what ideas you have in mind! Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
