title: Create session
description: Use the Vonage Video Server SDKs to learn how to create a session. Sessions allow participants to use audio, video, and messaging functionality in your application.
products:
  - video