title: Token creation
description: Learn how to create a token using the Vonage Video API Node.js SDK. Tokens allow participants to use audio, video, and messaging functionality in your application.
products:
  - video