title: Joining a session 
description: Learn how to connect to a Vonage Video API session so that participants can use audio, video, and messaging functionality in your application.
products:
  - video