title: Subscribe to streams
description: Learn how to subscribe to an Vonage Video API stream in your application. Once you have connected to a session, you can subscribe to a stream to view video, audio, and signalling data.
products:
  - video