title: Moderation 
description: Learn how to set up moderation for your video application using the Vonage Video API. With moderator privileges, you can force partipcants to disconnect from the session, or stop publishing to the session.
products:
  - video