title: Basic video chat 
description: Learn the basic concepts of the Vonage Video API platform, including how users can communicate through video, voice, and messaging. Explore a basic Vonage Video API flow.
products:
  - video

introduction:
  title: Introduction
  description: Learn the basic concepts of the Vonage Video API platform, including how users can communicate through video, voice, and messaging. Explore a basic Vonage Video API flow.
  content: |
    # Introduction
    In this tutorial you will learn the basic concepts of the Vonage Video API platform, including how users can communicate through video, voice, and messaging.

    For conceptual information on the video API, see the [General overview page](/video/overview).

tasks:
    - video/basic-video-chat/ios-swift/step-0
    - video/basic-video-chat/ios-swift/step-1
    - video/basic-video-chat/ios-swift/step-2
    - video/basic-video-chat/ios-swift/step-3
    - video/basic-video-chat/ios-swift/step-4
    - video/basic-video-chat/ios-swift/step-5
    - video/basic-video-chat/ios-swift/step-6
    - video/basic-video-chat/ios-swift/step-7
    - video/basic-video-chat/ios-swift/step-8