---
title: "进行应用内的语音通话"
description: "从 Web 应用向电话进行语音通话。"
products: 
    - "client-sdk"
introduction: 
    title: "任务简介"
    description: "本任务介绍如何使用 JavaScript Client SDK 从 Web 应用拨打电话。"
    content: "# 简介\n在本教程中，您将学习如何创建 Client SDK 应用程序，然后编写代码以便从您的 Web 应用向电话拨打电话。\n\n为此，您需要：\n\n* 使用 Client SDK 进行语音通话的 Web 应用程序。\n*可公开访问的 URL，其中提供有关如何处理呼叫的说明。您将使用 GitHub Gist 实现此目标。<a href=\"https://gist.github.com/\" target=\"_blank\">GitHub Gists</a> 是与他人共享代码段的一种简单方式。\n"
prerequisites: 
    - "create-nexmo-account"
    - "install-nodejs"
    - "client-sdk/install-node-client-sdk"
    - "install-nexmo-cli-beta"
    - "join-github"
tasks: 
    - "client-sdk/app-to-phone/create-ncco"
    - "client-sdk/app-to-phone/create-application"
    - "client-sdk/create-user"
    - "client-sdk/generate-jwt-alice"
    - "client-sdk/app-to-phone/js-code"
    - "client-sdk/app-to-phone/js-run"
conclusion: 
    title: "接下来做什么？"
    description: "您还可以使用 Client SDK 执行哪些操作？"
    content: "\n# 接下来做什么？\n使用 Client SDK 可以执行更多操作。我们想听听您有什么想法？请发送电子邮件至 [devrel@vonage.com](mailto:devrel@vonage.com) 联系我们\n\n请参阅 [Client SDK 文档](/client-sdk/overview)。\n"
