---
title: "进行应用到应用的语音通话"
description: "您从一个 Web 应用向另一个 Web 应用拨打电话。"
products: 
    - "client-sdk"
introduction: 
    title: "任务简介"
    description: "本任务介绍如何使用适用于 JavaScript 的 Client SDK 从一个 Web 应用向另一个 Web 应用进行语音通话。"
    content: "# 简介\n在本教程中，您将学习如何创建 Client SDK 应用程序，然后编写代码以便从您的一个 Web 应用向另一个 Web 应用拨打电话。\n\n为此，您将创建：\n\n* 使用 Client SDK 进行应用到应用的语音通话的 Web 应用程序。\n*可公开访问的 URL，其中提供有关如何处理呼叫的说明 <abbr title=\"Nexmo Call Control Object\">NCCO</abbr>。您将使用 GitHub Gist 实现此目标。<a href=\"https://gist.github.com/\" target=\"_blank\">GitHub Gists</a> 是与他人共享代码段的一种简单方式。从您的应用程序触发应用内呼叫时，Nexmo 将使用 GitHub Gist 中的 NCCO 并将呼叫转接至目标应用。\n"
prerequisites: 
    - "create-nexmo-account"
    - "install-nodejs"
    - "client-sdk/install-node-client-sdk"
    - "install-nexmo-cli-beta"
    - "join-github"
tasks: 
    - "client-sdk/app-to-app/create-ncco"
    - "client-sdk/app-to-app/create-application"
    - "client-sdk/app-to-app/create-users"
    - "client-sdk/app-to-app/generate-jwts"
    - "client-sdk/app-to-app/call-code"
    - "client-sdk/app-to-app/receive-code"
    - "client-sdk/app-to-app/run"
conclusion: 
    title: "接下来做什么？"
    description: "您还可以使用 Client SDK 执行哪些操作？"
    content: "\n# 接下来做什么？\n使用 Client SDK 可以执行更多操作。我们想听听您有什么想法？请发送电子邮件至 [devrel@vonage.com](mailto:devrel@vonage.com) 联系我们\n\n请参阅 [Client SDK 文档](/client-sdk/overview)。\n"
