title: Receiving a phone call in-app
description: You receive a call from a phone to your app
products: 
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the Android Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an Android application using kotlin and the Nexmo Android Client SDK, and then write the code to receive a phone call to your Android app from a phone.

    Two parts are needed to achieve this:

    * An Android application that will receive the voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-kotlin/).

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli-beta
- install-android-studio

tasks:
- client-sdk/phone-to-app/create-webhook-server
- client-sdk/phone-to-app/create-application
- buy-nexmo-number
- link-nexmo-number
- client-sdk/create-user
- client-sdk/generate-jwt-alice
- client-sdk/phone-to-app/create-project
- client-sdk/phone-to-app/add-permissions
- client-sdk/phone-to-app/main-screen
- client-sdk/phone-to-app/client
- client-sdk/phone-to-app/receive-call


conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?

    For the complete version please see the Android Studio project in the `phone-to-app-kotlin/phone-to-app` folder of the [git repository]([Github](https://github.com/nexmo-community/client-sdk-tutorials/) you've cloned.

    You can do a lot more with the Client SDK. See [Client SDK documentation](/client-sdk/overview) or review
    [Android Client SDK documentation](/sdk/stitch/android/index).

    We want to hear what ideas you have in mind? Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>

   
