title: Receiving a phone call in-app
description: You receive a call from a phone to your app
products:
  - client-sdk

introduction:
  title: Introduction to this task
  description: This task shows you how to handle an inbound call into your web app using the Android Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create an Android application using Kotlin and the Android Client SDK, and then write the code to receive a phone call to your Android app from a phone.

    Two parts are needed to achieve this:

    * An Android application that will receive the voice call using the Client SDK.
    * A publicly accessible URL that serves instructions on how to handle the call. To accomplish this, you will create a webhook server using <a href="https://nodejs.org/en/" target="_blank">Node.js</a>, <a href="https://expressjs.com/" target="_blank">Express</a> and <a href="https://github.com/localtunnel/localtunnel" target="_blank">localtunnel</a>.

    ## Video tutorial
    If you prefer to follow along by video, you can find this tutorial on <a href="https://www.youtube.com/watch?v=U24jjj3FTJE" target="_blank">YouTube</a>:
    <center style="aspect-ratio: 16 / 9;"><iframe width="100%" height="100%" src="https://www.youtube-nocookie.com/embed/U24jjj3FTJE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></center>

    ### Completed project
    If you would like to follow along without building the app yourself, the completed project is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) -  please see the [phone-to-app-kotlin](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-kotlin) folder.

    *This tutorial uses NexmoClient version 4.0*

prerequisites:
- create-nexmo-account
- install-nodejs
- install-nexmo-cli
- install-android-studio

tasks:
- client-sdk/phone-to-app/create-webhook-server
- client-sdk/phone-to-app/create-application
- buy-nexmo-number
- link-nexmo-number
- client-sdk/create-user-alice
- client-sdk/generate-jwt-alice
- client-sdk/phone-to-app/create-project
- client-sdk/phone-to-app/add-permissions
- client-sdk/phone-to-app/main-screen
- client-sdk/phone-to-app/client
- client-sdk/phone-to-app/receive-call


conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    The complete version of the project you just built is available on [Github](https://github.com/nexmo-community/client-sdk-tutorials) - please see the [phone-to-app-kotlin](https://github.com/nexmo-community/client-sdk-tutorials/tree/main/phone-to-app-kotlin) folder.

    You can do a lot more with the Client SDK:
    - read the [Client SDK documentation](/client-sdk/overview)
    - review the [Android Client SDK documentation](/sdk/stitch/android/index)
    - try the [Client SDK Android Samples](https://github.com/nexmo-community/client-sdk-android-samples) repository

    We want to hear what ideas you have in mind! Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>


