---
title: "接收应用内的电话呼叫"
description: "您收到从电话向应用进行的呼叫"
products: 
    - "client-sdk"
introduction: 
    title: "任务简介"
    description: "本任务介绍如何使用 JavaScript Client SDK 处理 Web 应用的呼入电话。"
    content: "# 简介\n在本教程中，您将学习如何创建 Client SDK 应用程序，然后编写代码以接收\n<abbr title=\"Public Switched Telephone Network\">PSTN</abbr> 呼入电话。\n\n为此，您将需要：\n\n* 通知服务座席有呼入电话并提供应答功能的 Web 应用程序\n* 可以处理入站 Webhook 并返回 <abbr title=\"Nexmo Call Control Object\">NCCO</abbr> 以将呼入电话转接到应用程序的 Webhook 服务器\n"
prerequisites: 
    - "create-nexmo-account"
    - "install-nodejs"
    - "install-node-client-sdk"
    - "install-nexmo-cli-beta"
    - "install-express"
    - "run-ngrok"
tasks: 
    - "client-sdk/create-application"
    - "buy-nexmo-number"
    - "link-nexmo-number"
    - "client-sdk/create-user"
    - "client-sdk/generate-jwt"
    - "client-sdk/phone-to-app/create-webhook-server"
    - "client-sdk/phone-to-app/code"
    - "client-sdk/phone-to-app/run"
conclusion: 
    title: "接下来做什么？"
    description: "您还可以使用 Client SDK 执行哪些操作？"
    content: "\n# 接下来做什么？\n使用 Client SDK 可以执行更多操作。我们想听听您有什么想法？请发送电子邮件至 [devrel@vonage.com](mailto:devrel@vonage.com) 联系我们\n\n请参阅 [Client SDK 文档](/client-sdk/overview)。\n"
