title: Building a web-based video conferencing app using the video express SDK
description: The video express SDK provides a quick way to add audio-video communication functionality to your web application.
products:
  - video

introduction:
  title: Introduction
  description: In this tutorial, you will learn how to quickly integrate the video functionality into the frontend of your app using the [video express SDK](/video/resources#client-sdks).
  content: |
    # Introduction
    In this tutorial, you will learn how to quickly integrate video functionality into the frontend of your app using the [video express SDK](/video/resources#client-sdks).

    Vonage video express is a JavaScript SDK for quickly creating a multiparty video conference web application. It serves as a wrapper around the Vonage video API.

prerequisites:
  - video/general-prerequisites/tools
  - video/general-prerequisites/video-api-account
  - video/create-video-conferencing-app-express/prerequisites/enable-video-express

tasks:
    - video/create-video-conferencing-app-express/javascript/code-template
    - video/create-video-conferencing-app-express/javascript/auth-setup
    - video/create-video-conferencing-app-express/javascript/testing
    - video/create-video-conferencing-app-express/javascript/extra


conclusion:
  title: What's next?
  description: The next step is to integrate the server-side SDK to handle authentication
  content: |

    # What's next?
    Once the frontend integration is complete, The next step is to create a server-side setup to generate the credentials needed for the frontend. For that, you can follow the [Generating session IDs and tokens on the server side](/video/tutorials/server-side-setup) tutorial.

    You can also learn more about the video platform concepts via the [overview page](/video/overview).

    We want to hear what ideas you have in mind! Contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
