current:
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Senior Community Manager'
    author-short-name: 'myrsini'
  - name: 'Paul Ardeleanu'
    email: 'paul.ardeleanu@vonage.com'
    role: 'Developer Relations Manager'
    twitter: 'pardel'
    author-short-name: 'paul-ardeleanu'
  - name: 'Dwane Hemmings'
    email: 'dwane.hemmings@vonage.com'
    role: "JavaScript Developer Advocate"
    twitter: 'lifelongdev'
    author-short-name: 'dwanehemmings'
  - name: 'Benjamin Aronov'
    email: 'benjamin.aronov@vonage.com'
    role: 'Online Community Manager'
    twitter: "AronovBenjamin"
    author-short-name: 'benjamin-aronov'
  - name: "Abdul Ajetunmobi"
    email: "abdul.ajetunmobi@vonage.com"
    role: "iOS Developer Advocate"
    twitter: "abdulajet"
    author-short-name: 'abdul-ajetunmobi'
  - name: "Clarisse Ng"
    email: "clarisse.ng@vonage.com"
    role: "Community Manager, APAC"
    twitter: 'ImClarisseng'
    author-short-name: 'clarisse-ng'
  - name: "Filippos Kyprianou"
    email: "filippos.kyprianou@vonage.com"
    role: "Startup Community Manager"
    twitter: "FilipposKyp"
    author-short-name: 'filippos-kyprianou'
  - name: "James Seconde"
    email: "jim.seconde@vonage.com"
    role: "PHP Developer Advocate"
    twitter: "secondej"
    author-short-name: 'jim-seconde'
  - name: "Karl Lingiah"
    email: "karl.lingiah@vonage.com"
    role: "Ruby Developer Advocate"
    twitter: "KarlLingiah"
    author-short-name: 'karl-lingiah'
  - name: "Richard Süselbeck"
    email: "richard.sueselbeck@vonage.com"
    role: "Head of Developer Relations"
    twitter: "sueselbeck"
    author-short-name: 'richard-süselbeck'
  - name: "Amanda Cavallaro"
    email: "Amanda.Cavallaro@vonage.com"
    role: "Developer Advocate"
    twitter: "amdcavallaro"
    author-short-name: 'amanda-cavallaro'
  - name: "Daniela Facchinetti"
    email: "daniela.facchinetti@vonage.com"
    role: "Developer Relations Coordinator"
    author-short-name: 'daniela-facchinetti'
  - name: "Nick Iati"
    email: "nick.iati@vonage.com"
    role: "Product Manager, Documentation"
    author-short-name: 'nick-iati'
  - name: "Lucinda Bone"
    email: "Lucinda.Bone@vonage.com"
    role: "Community Manager, EMEA"
    twitter: 'lucinda_bone'
    author-short-name: 'lucinda-bone'
  - name: "Zachary Powell"
    email: "Zachary.Powell@vonage.com"
    role: "Sr Android Developer Advocate"
    author-short-name: 'zachary-powell-1'
  - name: "Max Kahan"
    email: "Max.Kahan@vonage.com"
    role: "Python Developer Advocate"
    twitter: "max_does_tech"
    author-short-name: 'max-kahan'
  - name: "Sina Madani"
    email: "Sina.Madani@vonage.com"
    role: "Java Developer Advocate"
    twitter: "madani_sina"
    author-short-name: 'sina-madani'
  - name: 'Chris Tankersley'
    email: 'chris.tankersley@vonage.com'
    twitter: 'dragonmantank'
    role: 'Developer Advocate'
    author-short-name: 'christankersley'

