current:
  - name: 'Kelly Andrews'
    email: 'kelly.andrews@vonage.com'
    role: "JavaScript Developer Advocate"
    twitter: 'kellyjandrews'
  - name: 'Myrsini Koukiasa'
    email: 'myrsini.koukiasa@vonage.com'
    twitter: 'myrsiningos'
    role: 'Senior Community Manager'
  - name: 'Garann Means'
    role: "Developer Advocate"
    email: 'garann.means@vonage.com'
  - name: 'Paul Ardeleanu'
    email: 'paul.ardeleanu@vonage.com'
    role: 'Developer Relations Manager'
    twitter: 'pardel'
  - name: 'Dwane Hemmings'
    email: 'dwane.hemmings@vonage.com'
    role: "JavaScript Developer Advocate"
    twitter: 'lifelongdev'
  - name: 'Benjamin Aronov'
    email: 'benjamin.aronov@vonage.com'
    role: 'Online Community Manager'
    twitter: "AronovBenjamin"
  - name: "Mofi Rahman"
    email: "mofi.rahman@vonage.com"
    role: "Video Developer Advocate"
    twitter: "moficodes"
  - name: "Abdul Ajetunmobi"
    email: "abdul.ajetunmobi@vonage.com"
    role: "iOS Developer Advocate"
    twitter: "abdulajet"
  - name: "Clarisse Ng"
    email: "clarisse.ng@vonage.com"
    role: "Community Manager, APAC"
    twitter: 'ImClarisseng'
  - name: "Filippos Kyprianou"
    email: "filippos.kyprianou@vonage.com"
    role: "Startup Community Manager"
    twitter: "FilipposKyp"
  - name: "Cory Althoff"
    email: "cory.althoff@vonage.com"
    role: "Developer Advocate"
    twitter: "coryalthoff"
  - name: "James Seconde"
    email: "jim.seconde@vonage.com"
    role: "PHP Developer Advocate"
    twitter: "secondej"
  - name: "Karl Lingiah"
    email: "karl.lingiah@vonage.com"
    role: "Ruby Developer Advocate"
    twitter: "KarlLingiah"
  - name: "Richard Süselbeck"
    email: "richard.sueselbeck@vonage.com"
    role: "Head of Developer Relations"
    twitter: "sueselbeck"
  - name: "Amanda Cavallaro"
    email: "Amanda.Cavallaro@vonage.com"
    role: "Developer Advocate"
    twitter: "amdcavallaro"
  - name: "Daniela Facchinetti"
    email: "daniela.facchinetti@vonage.com"
    role: "Developer Relations Coordinator"
  - name: "Matt Hunt"
    email: "matt.hunt@vonage.com"
    role: ".Net Developer Advocate"
    twitter: "doesdotnet"
  - name: "Nick Iati"
    email: "nick.iati@vonage.com"
    role: "Product Manager, Documentation"
  - name: "Marco Ranieri"
    email: "Marco.Ranieri@vonage.com"
    role: "DocOps - Ruby Technical Lead"
  - name: "Lucinda Bone"
    email: "Lucinda.Bone@vonage.com"
    role: "Community Manager, EMEA"
    twitter: 'lucinda_bone'
  - name: "Zachary Powell"
    email: "Zachary.Powell@vonage.com"
    role: "Sr Android Developer Advocate"
  - name: "Max Kahan"
    email: "Max.Kahan@vonage.com"
    role: "Python Developer Advocate"





