title: Token Creation
description: Learn how to create a token using the Vonage Video API Java SDK. Tokens allow participants to use audio, video, and messaging functionality in your application.
products:
  - video


introduction:
  title: Introduction
  description: In this tutorial, you will learn how to generate a token using the Java SDK.
  content: |
    # Introduction
    In order to authenticate a user connecting to a session, a client must connect using a token (see [this overview](/video/guides/create-token)).

prerequisites:
  - video/general-prerequisites/video-api-account

tasks:
    - video/create-token/java
