title: Basic video chat 
description: Follow this tutorial to build basic text chat from scratch using the Vonage Video API. It is the quickest way to build a proof of concept for this functionality on the video platform. 
products:
  - video

introduction:
  title: Introduction
  description: Follow this tutorial to build basic text chat from scratch using the Vonage Video API. It is the quickest way to build a proof of concept for this functionality on the video platform. 
  content: |
    # Introduction
    In this tutorial you will learn to build basic text chat from scratch using the Android SDK.

    For conceptual information on the video API, see the [General overview page](/video/overview).

tasks:
    - video/text-chat/android/step-1
    - video/text-chat/android/step-2
    - video/text-chat/android/step-3
    - video/text-chat/android/step-4
    - video/text-chat/android/step-5
    - video/text-chat/android/step-6