title: Custom Audio Driver
description: Add a custom audio driver to your application using the Vonage Video API.
products:
  - video

introduction:
  title: Introduction
  description: Add a custom audio driver to your application using the Vonage Video API. 
  content: |
    # Introduction
    In this tutorial you will learn how to add a custom audio driver to your application using the Android SDK

    For conceptual information on the video API, see the [General overview page](/video/overview).

tasks:
    - video/custom-audio-driver/android/step-0
    - video/custom-audio-driver/android/step-1
    - video/custom-audio-driver/android/step-2
    - video/custom-audio-driver/android/step-3