title: Publishing Streams 
description: Learn how to publish Vonage Video API streams in your IOS (Objective C) application.
products:
  - video

introduction:
  title: Introduction
  content: |
    # Introduction
    Once you have [connected to a session](/video/tutorials/joining-a-session), you can publish a stream that other clients connected to the session can view.

    In this tutorial, you will learn how to publish streams.

tasks:
    - video/publish-streams/ios/2-initialize-publisher-object
    - video/publish-streams/ios/3-check-publish-capabilities
    - video/publish-streams/ios/4-check-camera-access
    - video/publish-streams/ios/5-publish-stream
    - video/publish-streams/ios/6-stop-publisher-stream
    - video/publish-streams/ios/7-get-statistics
    - video/publish-streams/ios/8-test-publisher-stream


conclusion:
  title: What's next?
  content: |

    # What's next?
    You can learn more about the video platform concepts used in this tutorial from the [overview page](/video/overview).

    If you happen to have any ideas in mind please contact us at <a href="mailto:devrel@vonage.com">devrel@vonage.com</a>
