title: Custom Video Capturing
description: Add custom video capturing to your application using the Vonage Video API.
products:
  - video

introduction:
  title: Introduction
  description: Add custom video capturing to your application using the Vonage Video API.
  content: |
    # Introduction
    In this tutorial you will learn to how to add custom video capturing to your application using the iOS SDK.

    For conceptual information on the video API, see the [General overview page](/video/overview).

tasks:
    - video/custom-video-capturing/ios/step-0
    - video/custom-video-capturing/ios/step-1
    - video/custom-video-capturing/ios/step-2